### ISSUE TITLE
Market Orders are Rejected with Non Zero Price Error

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#14]
Market Orders are Rejected with Non Zero Price Error

![image](https://github.com/pannet1/telegram-trades/assets/168721095/3e340d46-a206-4fc1-a3bf-7477bbea8d47)

Task file and Signal file attached for reference
[tasks.json](https://github.com/pannet1/telegram-trades/files/15229258/tasks.json)
[signals.csv](https://github.com/pannet1/telegram-trades/files/15229259/signals.csv)

**Comment by pannet1** [comment]
[fixed](https://github.com/pannet1/telegram-trades/compare/5699159bdc819dcbef3cad6dd3016076d3273e7f...07bb02edd10579e506d8fd98eb17c004953204b5)
