### ISSUE TITLE
Position is not getting exited even after SL is hit Similar to Yesterday

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#15]
Position is not getting exited even after SL is hit Similar to Yesterday

PREMIUM JACKPOT:
BUY #BANKNIFTY 48700 CE
ABOVE -420-425
TARGET- 25/70/100/200/250 Point 
SL-390

I had to manually exit the position @ 363.2 @ 09:49:49

09:49:49 | SELL | BANKNIFTY 8th MAY 48700 CE NFORepeatMore | MIS / MKT | 30 | 30 | 363.20 | COMPLETE

[tasks.json](https://github.com/pannet1/telegram-trades/files/15229385/tasks.json)
[signals.csv](https://github.com/pannet1/telegram-trades/files/15229386/signals.csv)

  },
    {
        "channel": "Premium jackpot",
        "id": 1171505550069866,
        "symbol": "NFO:BANKNIFTY08MAY24C48700",
        "entry_range": "420|425",
        "target_range": "450.0|495.0|525.0|625.0|675.0",
        "sl": 390,
        "quantity": "15|15|15|15|15",
        "action": "Buy",
        "timestamp": "2024-05-07 09:48:20",
        "q1": 15,
        "q2": 15,
        "tq": 30,
        "fn": "XXX",
        "price": 420.0,
        "ltp": 418.95,
        "pnl": 0,
        "entry": {
            "symbol": "BANKNIFTY08MAY24C48700",
            "quantity": 30,
            "side": "B",
            "price": "420.00",
            "trigger_price": "419.95",
            "average_price": "420.00",
            "filled_quantity": 30,
            "exchange": "NFO",
            "order_id": "24050700053617",
            "broker_timestamp": "07/05/2024 09:48:24",
            "product": "MIS",
            "remarks": "Premium jackpot",
            "order_type": "L",
            "Status": "complete"
        }
    }

**Comment by ravikanthvishnubhotla** [comment]
for non-exit even below SL case, there is NO Pending SL order placed in Open Order book..This was the situation yesterday aswell..which i was discussing with you

**Comment by pannet1** [comment]
```[2024-05-07 10:12:23,776] INFO: stop loss order: {'symbol': 'NFO:BANKNIFTY08MAY24P48900', 'side': 'S', 'quantity': 15, 'price': -0.05, 'trigger_price': 0.0, 'order_type': 'SL', 'product': 'N', 'remarks': 'Premium jackpot'}]
```
Trying to modify stop loss to entry price of market order (which is 0)

**Comment by ravikanthvishnubhotla** [comment]
Understood..In this case, for SL modification, can we take the entry price as captured in CSV file?

**Comment by pannet1** [comment]
entry price + or - 5 paise
