### ISSUE TITLE
Buy Limit Order got rejected 

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#17]
Buy Limit Order got rejected

    {
        "channel": "SmsOptionsPremium",
        "id": 2171514174851609,
        "symbol": "NFO:BANKNIFTY08MAY24C49700",
        "entry_range": "283.85",
        "target_range": "305|330|360|400",
        "sl": 241.0,
        "quantity": "15|15|15|15",
        "action": "Buy",
        "timestamp": "2024-05-08 09:45:48",
        "q1": 15,
        "q2": 15,
        "tq": 30,
        "fn": "rejected",
        "price": 283.85,
        "ltp": 3.7,
        "pnl": 0
    }

![image](https://github.com/pannet1/telegram-trades/assets/168721095/52cc57f1-b326-418c-9399-2d28244d39dc)

**Comment by pannet1** [comment]
try placing a manual order for 283.85 on this. how come they are having low range of circuits for this trading symbol ?

**Comment by ravikanthvishnubhotla** [comment]
Hi, I could not check this today..will check may be tomorrow

**Comment by pannet1** [comment]
283.85 is not the current market price, it is other way around. it seems i am trying to place order at 283.85 when the market is within a lower price band.
