### ISSUE TITLE
Lowest Price of the range is considered for SL instead of Highest range for MKT orders

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#18]
![image](https://github.com/pannet1/telegram-trades/assets/168721095/e4ebf42e-135d-44df-a3d8-e6f9beb80add)

    },
    {
        "channel": "SmsOptionsPremium",
        "id": 2171514215846619,
        "symbol": "NFO:BANKNIFTY08MAY24P48300",
        "entry_range": "260|280",
        "target_range": "305|330|360|400",
        "sl": 194.0,
        "quantity": "15|15|15|15",
        "action": "Buy",
        "timestamp": "2024-05-08 09:52:38",
        "q1": 15,
        "q2": 15,
        "tq": 30,
        "fn": "trail_or_target2",
        "price": 260.0,
        "ltp": 282.5,
        "pnl": 9361.5,
        "entry": {
            "symbol": "BANKNIFTY08MAY24P48300",
            "quantity": 30,
            "side": "B",
            "price": "0.00",
            "trigger_price": "00.00",
            "average_price": "291.70",
            "filled_quantity": 30,
            "exchange": "NFO",
            "order_id": "24050800066385",
            "broker_timestamp": "08/05/2024 09:52:42",
            "product": "MIS",
            "remarks": "SmsOptionsPremium",
            "order_type": "MKT",
            "Status": "complete"
        },
        "stop": {
            "symbol": "BANKNIFTY08MAY24P48300",
            "quantity": 30,
            "side": "S",
            "price": "193.95",
            "trigger_price": "194.00",
            "average_price": "0.00",
            "exchange": "NFO",
            "order_id": "24050800066574",
            "broker_timestamp": "08/05/2024 09:52:56",
            "product": "MIS",
            "remarks": "SmsOptionsPremium",
            "order_type": "SL",
            "Status": "trigger pending"
        },
        "trail": {
            "symbol": "BANKNIFTY08MAY24P48300",
            "quantity": 15,
            "side": "S",
            "price": "259.95",
            "trigger_price": "260.00",
            "average_price": "0.00",
            "exchange": "NFO",
            "order_id": "24050800067316",
            "broker_timestamp": "08/05/2024 09:53:42",
            "product": "MIS",
            "remarks": "SmsOptionsPremium",
            "order_type": "SL",
            "Status": "trigger pending"
        }
    },
    {

**Comment by pannet1** [comment]
what is lowest price range and highest price range here?

**Comment by ravikanthvishnubhotla** [comment]
260 is Lowest range and 280 is highest Price Range
SmsOptionsPremium | 2.17151E+15 | NFO:BANKNIFTY08MAY24P48300 | 260\|280 | 305\|330\|360\|400 | 194 | 15\|15\|15\|15 | Buy | 08-05-2024 09:52
-- | -- | -- | -- | -- | -- | -- | -- | --






</html>

**Comment by pannet1** [comment]
suppose if the market is at 280.05 we enter into market order buy. and immediately place stop loss at 280 (highest price so immediately stop is triggered). is this desirable and what you are asking ?

**Comment by ravikanthvishnubhotla** [comment]
No..I think you did not understand here..Here, i am referring to TSL for 2nd Lot..
This Situation would come only for 2nd Lot as for 1st Lot initial SL is always the SL from Telegram Signal
Did i explain it correctly?
