### ISSUE TITLE
MKT Position exited even though SL did not trigger

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#20]
m

There was not Cancel message from below Signal File..But still the trade got exited

Premium jackpot | 1.17152E+15 | NFO:BANKNIFTY15MAY24P48000 | 495 | 520.0\|565.0\|595.0\|695.0\|745.0 | 450 | 15\|15\|15\|15\|15 | Buy | 09-05-2024 11:49

![image](https://github.com/pannet1/telegram-trades/assets/168721095/23a41a84-1d38-4137-a037-08924675f930)

    {
        "channel": "Premium jackpot",
        "id": 1171523558734036,
        "symbol": "NFO:BANKNIFTY15MAY24P48000",
        "entry_range": "495",
        "target_range": "520.0|565.0|595.0|695.0|745.0",
        "sl": 450.0,
        "quantity": "15|15|15|15|15",
        "action": "Buy",
        "timestamp": "2024-05-09 11:49:47",
        "q1": 15,
        "q2": 15,
        "tq": 30,
        "fn": "XXX",
        "price": 495.0,
        "ltp": 499.7,
        "pnl": 0,
        "entry": {
            "symbol": "BANKNIFTY15MAY24P48000",
            "quantity": 30,
            "side": "B",
            "price": "0.00",
            "trigger_price": "00.00",
            "average_price": "499.40",
            "filled_quantity": 30,
            "exchange": "NFO",
            "order_id": "24050900172928",
            "broker_timestamp": "09/05/2024 11:49:51",
            "product": "MIS",
            "remarks": "Premium jackpot",
            "order_type": "MKT",
            "Status": "complete"
        },
        "stop": {
            "symbol": "BANKNIFTY15MAY24P48000",
            "quantity": 30,
            "side": "S",
            "price": "449.95",
            "trigger_price": "450.00",
            "average_price": "0.00",
            "exchange": "NFO",
            "order_id": "24050900173141",
            "broker_timestamp": "09/05/2024 11:50:03",
            "product": "MIS",
            "remarks": "Premium jackpot",
            "order_type": "SL",
            "Status": "trigger pending"
        }
    }
]

{'channel': 'Premium jackpot', 'id': 1171523544610318, 'symbol': 'NFO:BANKNIFTY15MAY24P48000', 'entry_range': '540|550', 'target_range': '575.0|620.0|650.0|750.0|800.0', 'sl': 500.0, 'quantity': '15|15|15|15|15', 'action': 'Cancel', 'timestamp': '2024-05-09 11:47:26', 'fn': 'do_cancel'}, {'channel': 'Premium jackpot', 'id': 1171523558734036, 'symbol': 'NFO:BANKNIFTY15MAY24P48000', 'entry_range': '495', 'target_range': '520.0|565.0|595.0|695.0|745.0', 'sl': 450.0, 'quantity': '15|15|15|15|15', 'action': 'Buy', 'timestamp': '2024-05-09 11:49:47', 'q1': 15, 'q2': 15, 'tq': 30, 'fn': 'stop1', 'price': 495.0, 'ltp': 499.7, 'pnl': 0, 'entry': {'symbol': 'BANKNIFTY15MAY24P48000', 'quantity': 30, 'side': 'B', 'price': '0.00', 'trigger_price': '00.00', 'average_price': '499.40', 'filled_quantity': 30, 'exchange': 'NFO', 'order_id': '24050900172928', 'broker_timestamp': '09/05/2024 11:49:51', 'product': 'MIS', 'remarks': 'Premium jackpot', 'order_type': 'MKT', 'Status': 'complete'}}], 'channel': 'Premium jackpot', 'symbol': 'NFO:BANKNIFTY15MAY24P48000', 'task': {'channel': 'Premium jackpot', 'id': 1171523558734036, 'symbol': 'NFO:BANKNIFTY15MAY24P48000', 'entry_range': '495', 'target_range': '520.0|565.0|595.0|695.0|745.0', 'sl': 450.0, 'quantity': '15|15|15|15|15', 'action': 'Buy', 'timestamp': '2024-05-09 11:49:47', 'q1': 15, 'q2': 15, 'tq': 30, 'fn': 'stop1', 'price': 495.0, 'ltp': 499.7, 'pnl': 0, 'entry': {'symbol': 'BANKNIFTY15MAY24P48000', 'quantity': 30, 'side': 'B', 'price': '0.00', 'trigger_price': '00.00', 'average_price': '499.40', 'filled_quantity': 30, 'exchange': 'NFO', 'order_id': '24050900172928', 'broker_timestamp': '09/05/2024 11:49:51', 'product': 'MIS', 'remarks': 'Premium jackpot', 'order_type': 'MKT', 'Status': 'complete'}}, 'order': {'symbol': 'BANKNIFTY15MAY24P48000', 'quantity': 30, 'side': 'B', 'price': '0.00', 'trigger_price': '00.00', 'average_price': '499.40', 'filled_quantity': 30, 'exchange': 'NFO', 'order_id': '24050900172928', 'broker_timestamp': '09/05/2024 11:49:51', 'product': 'MIS', 'remarks': 'Premium jackpot', 'order_type': 'MKT', 'Status': 'complete'}, 'e': UnboundLocalError("local variable 'side' referenced before assignment")}
        Error message: local variable 'side' referenced before assignment
        
    ]
Traceback (most recent call last):
  File "C:\py\venv\telegram-trades\telegram_trades\main.py", line 417, in do_cancel
    market_order(self.api, order, "opposite")
  File "C:\py\venv\telegram-trades\telegram_trades\main.py", line 139, in market_order
    side=side,
UnboundLocalError: local variable 'side' referenced before assignment
[2024-05-09 11:50:03,652] INFO: stop args: {'symbol': 'NFO:BANKNIFTY15MAY24P48000', 'side': 'S', 'quantity': 30, 'price': 449.95, 'trigger_price': 450.0, 'order_type': 'SL', 'product': 'N', 'remarks': 'Premium jackpot'}]
[2024-05-09 11:50:08,313] INFO: modify SL {'order_id': '24050900173141', 'symbol': 'NFO:BANKNIFTY15MAY24P48000', 'side': 'S', 'quantity': 30, 'price': 0.0, 'order_type': 'MKT', 'product': 'N'} to tgt got {'stat': 'Ok', 'nestOrderNumber': '24050900173141'}]
[2024-05-09 11:50:08,313] INFO: cancel stop: None]

**Comment by ravikanthvishnubhotla** [comment]
Attached Log file for reference

[file.log](https://github.com/pannet1/telegram-trades/files/15258973/file.log)

**Comment by pannet1** [comment]
you mean to say for this channel and this tradingsymbol there was no cancel message for the whole day  ?
 
 "remarks": "Premium jackpot",
 NFO:BANKNIFTY15MAY24P48000",

**Comment by ravikanthvishnubhotla** [comment]
There were 8 Trades where Position Exits were made even with out Price Hitting SL..This happened in Two Channels out of 4

},
    {
        "channel": "Premium jackpot",
        "id": 1171522831253900,
        "symbol": "NFO:BANKNIFTY15MAY24P48200",
        "entry_range": "480",
        "target_range": "510.0|550.0|580.0|680.0|730.0",
        "sl": 440,
        "quantity": "15|15|15|15|15",
        "action": "Buy",
        "timestamp": "2024-05-09 09:48:32",
        "q1": 15,
        "q2": 15,
        "tq": 30,
        "fn": "XXX",
        "price": 480.0,
        "ltp": 484.65,
        "pnl": 0,
        "entry": {
            "symbol": "BANKNIFTY15MAY24P48200",
            "quantity": 30,
            "side": "B",
            "price": "0.00",
            "trigger_price": "00.00",
            "average_price": "484.55",
            "filled_quantity": 30,
            "exchange": "NFO",
            "order_id": "24050900053888",
            "broker_timestamp": "09/05/2024 09:48:52",
            "product": "MIS",
            "remarks": "Premium jackpot",
            "order_type": "MKT",
            "Status": "complete"
        },
        "stop": {
            "symbol": "BANKNIFTY15MAY24P48200",
            "quantity": 30,
            "side": "S",
            "price": "439.95",
            "trigger_price": "440.00",
            "average_price": "0.00",
            "exchange": "NFO",
            "order_id": "24050900054755",
            "broker_timestamp": "09/05/2024 09:49:20",
            "product": "MIS",
            "remarks": "Premium jackpot",
            "order_type": "SL",
            "Status": "trigger pending"
        }
    },
