### ISSUE TITLE
Aliceblue Error: Order Not Open Cancel Still coming

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#21]
This Error

 {
        "channel": "Premium jackpot",
        "id": 1171531300397924,
        "symbol": "NFO:BANKNIFTY15MAY24C47400",
        "entry_range": "490|500",
        "target_range": "530.0|570.0|600.0|700.0|750.0",
        "sl": 440,
        "quantity": "15|15|15|15|15",
        "action": "Cancel",
        "timestamp": "2024-05-10 09:20:03",
        "fn": "XXX"
    },
    {
        "channel": "Premium jackpot",
        "id": 1171531311272335,
        "symbol": "NFO:BANKNIFTY15MAY24C47400",
        "entry_range": "460|470",
        "target_range": "500.0|540.0|570.0|670.0|720.0",
        "sl": 400,
        "quantity": "15|15|15|15|15",
        "action": "Buy",
        "timestamp": "2024-05-10 09:21:52",
        "q1": 15,
        "q2": 15,
        "tq": 30,
        "fn": "XXX",
        "price": 470.0,
        "ltp": 468.6,
        "pnl": 0,
        "entry": {
            "symbol": "BANKNIFTY15MAY24C47400",
            "quantity": 30,
            "side": "B",
            "price": "470.00",
            "trigger_price": "00.00",
            "average_price": "0.00",
            "exchange": "NFO",
            "order_id": "24051000014409",
            "broker_timestamp": "10/05/2024 09:21:55",
            "product": "MIS",
            "remarks": "Premium jackpot",
            "order_type": "L",
            "Status": "open"
        }
    },
    {
        "channel": "Premium jackpot",
        "id": 1171531315340269,
        "symbol": "BFO:SENSEX2451072200CE",
        "entry_range": "400",
        "target_range": "430.0|470.0|500.0|600.0|650.0",
        "sl": 350,
        "quantity": "10|10|10|10|10",
        "action": "Buy",
        "timestamp": "2024-05-10 09:22:33",
        "q1": 10,
        "q2": 10,
        "tq": 20,
        "fn": "rejected",
        "price": 400.0,
        "ltp": 400.9,
        "pnl": 0
    }
]

![image](https://github.com/pannet1/telegram-trades/assets/168721095/bc02b3d3-05fe-4807-96df-0a883644ff75)

![image](https://github.com/pannet1/telegram-trades/assets/168721095/e0d9ec5e-5b44-4d19-b284-0459605eed95)

**Comment by pannet1** [comment]
#16
