### ISSUE TITLE
Slippage Issue: Ex. Stock Options

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#25]
I have some observation regarding Order Placement..I think still the orders are placed @ Market instead of Limit  once the Limit Price is Hit?..for Stock Options i observed that MKT orders are triggered once Limit Price is reached, which is causing substantial slippage
Can you find a way out to address this..I think the same should be happening with Index Options aswell
Maruti was to be taken @ 225, it took at 237.72, which means 12.72*50=636 Slippage per Lot
IRCTC was to be taken @ 20, it took at 42.47, which means 22.47*850=19099.5 Slippage per Lot..
Can you check this
![image](https://github.com/pannet1/telegram-trades/assets/168721095/6591e7f9-a6bb-455f-a2cf-66a6973ab5c6)

**Comment by pannet1** [comment]
added new IGNORE marker and entries with LIMIT Price will now live for more than maximum of 15 minutes

**Comment by ravikanthvishnubhotla** [comment]
added new IGNORE marker and entries with LIMIT Price will now live for more than maximum of 15 minutes
will Not Live More than Max of 15 minutes?
