### ISSUE TITLE
FUTURE BUY is not working

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#29]
Hi Karthi, As per Out last discussion, Future Buy should be working..But trades are not getting triggered in Terminal, eventhough there is signal in Signals.CSV and No Entry made in Log File & Tasks 
[tasks.json](https://github.com/user-attachments/files/16049696/tasks.json)
[file.log](https://github.com/user-attachments/files/16049698/file.log)
aswell..Can you check Order Management once

Premium jackpot	1.17198E+15	NFO:MGL25JUL24F	1674	1684|1700|1800	1660	400	BUY	01-07-2024 12:47
Premium jackpot	1.17198E+15	NFO:MGL25JUL24F	1680	1690|1720|1800	1665	400	BUY	01-07-2024 12:51
Premium jackpot	1.17198E+15	NFO:MGL25JUL24F	1680	1690|1720|1800	1665	400	CANCEL	01-07-2024 12:56
Premium jackpot	1.17198E+15	NFO:MGL25JUL24F	1685	1695|1720|1800	1665	400	BUY	01-07-2024 12:59
[file.log](https://github.com/user-attachments/files/16049683/file.log)

**Comment by pannet1** [comment]
i could see other stocks are traded today. after market is over, you could enter it separately and test it.  i cant find out any reference to this trade from the files. so we need to isolate it and test it after market.

**Comment by ravikanthvishnubhotla** [comment]
Hi @pannet1 , while firing the command Manually, Order is placed in the Terminal..But not from Order Management system..Can you check this

**Comment by ravikanthvishnubhotla** [comment]
Yes, it is..I checked last time and Order triggered after running main.py
