### ISSUE TITLE
Trailing stops lagging..Refer #26

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#30]
PlatinumMembers  1.2172E+16  NFO:BANKNIFTY03JUL24C52600  310  331|352|373|394|415|436|457|478|499|520  277  15|15  Buy  12-04-2658 20:50
when the LTP is above 415 also, it did not trail beyond 373.

Attached Tasks.Jason file and 52600 CE Log file of today
{
        "channel": "PlatinumMembers",
        "id": 12171997843347599,
        "symbol": "NFO:BANKNIFTY03JUL24C52600",
        "entry_range": "310",
        "target_range": "331|352|373|394|415|436|457|478|499|520",
        "sl": 277,
        "quantity": "15|15",
        "action": "Buy",
        "timestamp": "2658-04-12 20:50:33",
        "q1": 15,
        "q2": 15,
        "tq": 30,
        "fn": "TRAILED-OUT",
        "ltp": 398.65,
        "price": 310.0,
        "entry": {
            "symbol": "BANKNIFTY03JUL24C52600",
            "quantity": 30,
            "side": "B",
            "price": "310.00",
            "trigger_price": "309.95",
            "average_price": "310.00",
            "filled_quantity": 30,
            "exchange": "NFO",
            "order_id": "24070300010082",
            "broker_timestamp": "03/07/2024 09:21:08",
            "product": "MIS",
            "remarks": "PlatinumMembers",
            "order_type": "L",
            "Status": "complete"
        },
        "stop": {
            "symbol": "BANKNIFTY03JUL24C52600",
            "quantity": 30,
            "side": "S",
            "price": "276.95",
            "trigger_price": "277.00",
            "average_price": "0.00",
            "exchange": "NFO",
            "order_id": "24070300021058",
            "broker_timestamp": "03/07/2024 09:21:27",
            "product": "MIS",
            "remarks": "PlatinumMembers",
            "order_type": "SL",
            "Status": "trigger pending"
        },
        "pnl": 2557.5,
        "trail": {
            "symbol": "BANKNIFTY03JUL24C52600",
            "quantity": 15,
            "side": "S",
            "price": "372.95",
            "trigger_price": "373.00",
            "average_price": "373.00",
            "filled_quantity": 15,
            "exchange": "NFO",
            "order_id": "24070300022264",
            "broker_timestamp": "03/07/2024 09:23:07",
            "product": "MIS",
            "remarks": "PlatinumMembers",
            "order_type": "L",
            "Status": "complete"
        }
    },
[file.log](https://github.com/user-attachments/files/16076950/file.log)
[tasks.json](https://github.com/user-attachments/files/16076952/tasks.json)

**Comment by ravikanthvishnubhotla** [comment]
[53000 CE.txt](https://github.com/user-attachments/files/16077073/53000.CE.txt)
Similar Observation with another instrument..53000 CE
SmsOptionsPremium  2.172E+15  NFO:BANKNIFTY03JUL24C53000  280|300  321|342|363|384|405|426|447|469|490|511  265  15|15  Buy  03-07-2024 09:41
it did not trail to 342 even when the price went till 370
![image](https://github.com/pannet1/telegram-trades/assets/168721095/fe576da7-9c46-4204-a7ec-f4e53f829645)
[tasks.json](https://github.com/user-attachments/files/16077068/tasks.json)

**Comment by pannet1** [comment]
@ravikanthvishnubhotla can you please check the trailing log as mentioned in telegram for atleast one case. what was the LTP according to log when we were checking trail every time, till the order is closed.

**Comment by pannet1** [comment]
@ravikanthvishnubhotla added symbol name to the trailing so that we will know what symbol, the trailing is actually for. can you please git pull once.

**Comment by ravikanthvishnubhotla** [comment]
Signals

BnoPremium  5.17202E+15  NFO:BANKNIFTY10JUL24P52500  310|320  342|364|386|407|429|451|473|495|517|539  286  15|15  Buy  05-07-2024 09:23
PaidCallPut  3.17202E+15  NFO:BANKNIFTY10JUL24P52500  330|320  351|372|394|415|436|457|479|500|521|542  296  15|15  Buy  05-07-2024 09:23

Executed Orders
UserId  Time  Type  Instrument  Product  Qty.  Price  Status
172259  09:36:55  SELL  BANKNIFTY 10th JUL 52500 PE  MIS / L  15  473  / 473.00 trg.  COMPLETE
172259  09:36:23  SELL  BANKNIFTY 10th JUL 52500 PE  MIS / L  15  478.95  / 479.00 trg.  COMPLETE
172259  09:25:45  SELL  BANKNIFTY 10th JUL 52500 PE  MIS / MKT  15  353.4  / 296.00 trg.  COMPLETE
172259  09:24:52  BUY  BANKNIFTY 10th JUL 52500 PE  MIS / L  30  330  COMPLETE
172259  09:24:10  SELL  BANKNIFTY 10th JUL 52500 PE  MIS / MKT  15  343.7  / 286.00 trg.  COMPLETE
172259  09:23:06  BUY  BANKNIFTY 10th JUL 52500 PE  MIS / L  30  320  COMPLETE

As you can see, 2nd Lot of both the Trades are exited with TSL @ 473 & 479 respectively, where as the high for BANKNIFTY10JUL24P52500 is 571

It should have trailed atleast upto 539&542 respectively since the high was 571, or atleast till 517 & 521 at minimum, assuming the price spiked- later

![image](https://github.com/pannet1/telegram-trades/assets/168721095/0859d615-361e-43df-8f69-20624921e3ec)
[tasks.json](https://github.com/user-attachments/files/16104857/tasks.json)
[file.log](https://github.com/user-attachments/files/16104858/file.log)

**Comment by pannet1** [comment]
the commit 1a3f7b53db99adc273591e6101e2fef8a98e9437 solved the issue. also made some attempts to improve speed.
