### ISSUE TITLE
Files in VPS are not updated with MKT order Code

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#6]
Files in VPS are not updated with MKT order Code
![image](https://github.com/pannet1/telegram-trades/assets/168721095/a3b1119c-374a-4de4-99ed-2bdfb0ee8bbc)
![MKT order issue](https://github.com/pannet1/telegram-trades/assets/168721095/00dde8fc-03ef-44a7-a846-4f68aa8bbee9)

**Comment by pannet1** [comment]
@ravikanthvishnubhotla 
very good catch. please try to do a git pull at your end and post any errors if any

![image](https://github.com/pannet1/telegram-trades/assets/12350276/cd46cefe-95e3-4b03-8d87-abc9c27c3275)

**Comment by ravikanthvishnubhotla** [comment]
> @ravikanthvishnubhotla very good catch. please try to do a git pull at your end and post any errors if any
> 
> ![image](https://private-user-images.githubusercontent.com/12350276/327387926-cd46cefe-95e3-4b03-8d87-abc9c27c3275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDQxNjMsIm5iZiI6MTcxNDY0Mzg2MywicGF0aCI6Ii8xMjM1MDI3Ni8zMjczODc5MjYtY2Q0NmNlZmUtOTVlMy00YjAzLThkODctYWJjOWMyN2MzMjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDA5NTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiOGNhYTlmYjExMTJhMDEwNjQzMTI0ZWQwODA3NjY1NmY0Y2Y0YmMzMmVjMTBiNzZkNjZmMTZkN2JmMmNmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JvwSDLNUBwLHWHKQ7Ahsh7xMbUCt1yjsfA8drZodXH4)

I did git Pull in VPS..
![image](https://github.com/pannet1/telegram-trades/assets/168721095/d463aee7-318a-4033-b3ef-2b2b6b2bfb19)
but, still the timestamp of main.py is not updated??
