### ISSUE TITLE
Execution Error in Main.py and Unknown Error in Json

### ISSUE THREAD

**Issue by ravikanthvishnubhotla** [pannet1/telegram-trades#7]
Below Execution Error in Main.py
![image](https://github.com/pannet1/telegram-trades/assets/168721095/789f0fab-6af2-4648-9a9f-fccf6f596e3f)

{
        "channel": "Premium jackpot",
        "id": 1171470793851327,
        "symbol": "NFO:BANKNIFTY08MAY24P49600",
        "entry_range": "390|400",
        "target_range": "430.0|470.0|500.0|600.0|650.0",
        "sl": 350,
        "quantity": "15|15|15|15|15",
        "action": "Buy",
        "timestamp": "2024-05-03 09:15:38",
        "q1": 15,
        "q2": 15,
        "tq": 30,
        "fn": "UNKNOWN",
        "price": 0.0,
        "ltp": 401.95,
        "pnl": 0
    }
]

**Comment by pannet1** [comment]
fixed and git pull complete
